// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonasABM.Infrastructure.Data;

#nullable disable

namespace PersonasABM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251008141700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PersonasABM.Domain.Entities.AtributoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("atributo_tipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "¿La persona maneja vehículos?",
                            EsObligatorio = false,
                            FechaCreacion = new DateTime(2025, 10, 8, 14, 16, 59, 371, DateTimeKind.Utc).AddTicks(8766),
                            Nombre = "Maneja",
                            TipoDato = "Booleano"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "¿La persona usa lentes correctivos?",
                            EsObligatorio = false,
                            FechaCreacion = new DateTime(2025, 10, 8, 14, 16, 59, 371, DateTimeKind.Utc).AddTicks(8775),
                            Nombre = "Usa Lentes",
                            TipoDato = "Booleano"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "¿La persona tiene diabetes?",
                            EsObligatorio = false,
                            FechaCreacion = new DateTime(2025, 10, 8, 14, 16, 59, 371, DateTimeKind.Utc).AddTicks(8781),
                            Nombre = "Es Diabético",
                            TipoDato = "Booleano"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Tipo de sangre de la persona",
                            EsObligatorio = false,
                            FechaCreacion = new DateTime(2025, 10, 8, 14, 16, 59, 371, DateTimeKind.Utc).AddTicks(8783),
                            Nombre = "Tipo de Sangre",
                            TipoDato = "Texto"
                        });
                });

            modelBuilder.Entity("PersonasABM.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtributosAdicionales")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("personas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtributosAdicionales = "{\"Maneja\": true, \"Usa Lentes\": false, \"Es Diabético\": false, \"Tipo de Sangre\": \"O+\"}",
                            Edad = 35,
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2025, 10, 8, 14, 16, 59, 371, DateTimeKind.Utc).AddTicks(9206),
                            Genero = "Masculino",
                            Identificacion = "12345678",
                            NombreCompleto = "Juan Pérez García"
                        },
                        new
                        {
                            Id = 2,
                            AtributosAdicionales = "{\"Maneja\": true, \"Usa Lentes\": true, \"Es Diabético\": true, \"Tipo de Sangre\": \"A+\"}",
                            Edad = 28,
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2025, 10, 8, 14, 16, 59, 371, DateTimeKind.Utc).AddTicks(9209),
                            Genero = "Femenino",
                            Identificacion = "87654321",
                            NombreCompleto = "María López Rodríguez"
                        });
                });

            modelBuilder.Entity("PersonasABM.Domain.Entities.PersonaAtributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtributoTipoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtributoTipoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("persona_atributos", (string)null);
                });

            modelBuilder.Entity("PersonasABM.Domain.Entities.PersonaAtributo", b =>
                {
                    b.HasOne("PersonasABM.Domain.Entities.AtributoTipo", "AtributoTipo")
                        .WithMany("PersonaAtributos")
                        .HasForeignKey("AtributoTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonasABM.Domain.Entities.Persona", "Persona")
                        .WithMany("PersonaAtributos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtributoTipo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PersonasABM.Domain.Entities.AtributoTipo", b =>
                {
                    b.Navigation("PersonaAtributos");
                });

            modelBuilder.Entity("PersonasABM.Domain.Entities.Persona", b =>
                {
                    b.Navigation("PersonaAtributos");
                });
#pragma warning restore 612, 618
        }
    }
}
